spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: 0945057018
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8080
  servlet:
    context-path: /identity
jwt:
  signerKey: "GPBo75zMtI2yFQLTDMlnzy0IbaXp7XI8bIQLOXwkVs2SjHPHuYEJyA74ZRYPeP86"